version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Todo@1234"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql  # Persistent data
volumes:
  sqlserver_data:
